import { Gabarito, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const roboto = Roboto({ 
  subsets: ["latin"],
  weight: ["400", "500", "700"] 
});

export const metadata = {
  title: "JUST-A",
  description: "Generated by samid",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-color-dark scroll-smooth`} suppressHydrationWarning={true}>
        <Navbar />
        <div className="bg-gradient-to-t from-color-dark via-50% to-black">
          {children}
        </div>
      </body>
    </html>
  );
}
